fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /registrar-usuario

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_admin_users:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /admin

login_check:
    path:   /login_check

logout:
    path: /logout