# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
      AppBundle\Entity\Usuarios:
         algorithm:        sha1
         encode_as_base64: false
         iterations:       1

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_VENDEDOR, ROLE_COBRADOR, ROLE_GERENTE_FINANZAS, ROLE_GERENTE_VENTAS ]
        ROLE_SUPER_ADMIN: [ ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN ]

    providers:
        administrators:
            entity: { class: AppBundle:Usuarios, property: nombreUsuario }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout
                target: /

    access_control:
            # - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
