# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_VENDEDOR, ROLE_COBRADOR, ROLE_GERENTE_FINANZAS, ROLE_GERENTE_VENTAS ]
        ROLE_SUPER_ADMIN: [ ROLE_SUPER_ADMIN, ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN ]

    providers:
            fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  login
                check_path:  login_check
            logout:
                path:   /logout
                target: /

    access_control:
            - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
