# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    fos_user.doctrine_registry:
        alias: doctrine
    doctrine.details_listener:
        class: AppBundle\EventListener\NumberGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    doctrine.supplier_listener:
        class: AppBundle\EventListener\CodeGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"