# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    doctrine.details_listener:
        class: AppBundle\EventListener\NumberGeneratorListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
