bodega_index:
    path:     /
    defaults: { _controller: "AppBundle:Bodega:index" }
    methods:  GET

bodega_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Bodega:show" }
    methods:  GET

bodega_new:
    path:     /new
    defaults: { _controller: "AppBundle:Bodega:new" }
    methods:  [GET, POST]

bodega_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Bodega:edit" }
    methods:  [GET, POST]

bodega_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Bodega:delete" }
    methods:  DELETE
