cobradores_index:
    path:     /
    defaults: { _controller: "AppBundle:Cobradores:index" }
    methods:  GET

cobradores_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Cobradores:show" }
    methods:  GET

cobradores_new:
    path:     /new
    defaults: { _controller: "AppBundle:Cobradores:new" }
    methods:  [GET, POST]

cobradores_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Cobradores:edit" }
    methods:  [GET, POST]

cobradores_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Cobradores:delete" }
    methods:  DELETE
