collectors_index:
    path:     /
    defaults: { _controller: "AppBundle:Collectors:index" }
    methods:  GET

collectors_sale:
    path:     /{id}/detalles-compra
    defaults: { _controller: "AppBundle:Collectors:collectorSale" }
    methods:  [GET, POST]

collectors_movements_sale:
    path:     /{id}/detalle-movimiento
    defaults: { _controller: "AppBundle:Collectors:movementsDetail" }
    methods:  [GET, POST]
