historialdeudor_index:
    path:     /
    defaults: { _controller: "AppBundle:HistorialDeudor:index" }
    methods:  GET

historialdeudor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:HistorialDeudor:show" }
    methods:  GET

historialdeudor_new:
    path:     /new
    defaults: { _controller: "AppBundle:HistorialDeudor:new" }
    methods:  [GET, POST]

historialdeudor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:HistorialDeudor:edit" }
    methods:  [GET, POST]

historialdeudor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:HistorialDeudor:delete" }
    methods:  DELETE
