manager_index:
    path:     /
    defaults: { _controller: "AppBundle:Manager:index" }
    methods:  GET

manager_show:
    path:     /{id}/detalle
    defaults: { _controller: "AppBundle:Manager:show" }
    methods:  GET