movimientos_index:
    path:     /
    defaults: { _controller: "AppBundle:Movimientos:index" }
    methods:  GET

movimientos_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Movimientos:show" }
    methods:  GET

movimientos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Movimientos:new" }
    methods:  [GET, POST]

movimientos_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Movimientos:edit" }
    methods:  [GET, POST]

movimientos_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Movimientos:delete" }
    methods:  DELETE
