operators_index:
    path:     /
    defaults: { _controller: "AppBundle:Operator:index" }
    methods:  GET

operators_show:
    path:     /{id}/detalle
    defaults: { _controller: "AppBundle:Operator:show" }
    methods:  GET

operators_register:
    path:     /registrar
    defaults: { _controller: "AppBundle:Operator:register" }
    methods:  [GET, POST]

operators_edit:
    path:     /{id}/editar
    defaults: { _controller: "AppBundle:Operator:edit" }
    methods:  [POST, DELETE, GET ]

operators_delete:
    path:     /{id}/eliminar
    defaults: { _controller: "AppBundle:Operator:delete" }
    methods:  DELETE

product_operators_json_index:
    path:     /json_productos
    defaults: { _controller: "AppBundle:Operator:jsonProducts" }
    methods:  GET

json_cart_all_json_index:
    path:     /json-cart-all-json
    defaults: { _controller: "AppBundle:Operator:jsonCartAll" }
    methods:  [ POST, GET ]

json_shopping_cart_json_index:
    path:     /json-shopping-cart
    defaults: { _controller: "AppBundle:Operator:jsonShoppingCart" }
    methods:  [ POST, GET ]

json_shopping_cart_json_delete:
    path:     /{id}/json-shopping-cart-delete
    defaults: { _controller: "AppBundle:Operator:jsonShoppingDelete" }
    methods:  [ DELETE, GET ]

json_shopping_cart_json_update:
    path:     /{id}/json-shopping-cart-edit
    defaults: { _controller: "AppBundle:Operator:jsonShoppingUpdate" }
    methods:  POST

product_operators_index:
    path:     /productos
    defaults: { _controller: "AppBundle:Operator:products" }
    methods:  GET

product_operators_show:
    path:      /{id}/producto
    defaults: { _controller: "AppBundle:Operator:showProduct" }
    methods:  GET