sellers_index:
    path:     /
    defaults: { _controller: "AppBundle:Sellers:index" }
    methods:  GET

sellers_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sellers:show" }
    methods:  GET

sellers_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sellers:new" }
    methods:  [GET, POST]

sellers_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sellers:edit" }
    methods:  [GET, POST]

sellers_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sellers:delete" }
    methods:  DELETE

sellers_supplier:
    path:     /registrar-proveedor
    defaults: { _controller: "AppBundle:Sellers:registerSupplier" }
    methods:  [GET, POST]

sellers_details:
    path:     /{id}/detalles-compra
    defaults: { _controller: "AppBundle:Sellers:detailsRegister" }
    methods:  [GET, POST]

sellers_details_c:
    path:     /detalles
    defaults: { _controller: "AppBundle:Sellers:listDetails" }
    methods:  GET

sellers_list_product:
    path:     /lista-productos
    defaults: { _controller: "AppBundle:Sellers:listProducts" }
    methods:  GET

sellers_view_product:
    path:     /{id}/producto
    defaults: { _controller: "AppBundle:Sellers:showProduct" }
    methods:  [GET, POST]

sellers_record_sale_product:
    path:     /registrar-venta
    defaults: { _controller: "AppBundle:Sellers:recordSale" }
    methods:  [GET, POST]