users_index:
    path:     /
    defaults: { _controller: "AppBundle:Users:index" }
    methods:  GET

users_show:
    path:     /{id}/perfil
    defaults: { _controller: "AppBundle:Users:show" }
    methods:  GET

users_new:
    path:     /nuevo-usuario
    defaults: { _controller: "AppBundle:Users:new" }
    methods:  [GET, POST]

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Users:edit" }
    methods:  [POST, DELETE, GET ]

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Users:delete" }
    methods:  [GET, DELETE ]

