usuarios_index:
    path:     /
    defaults: { _controller: "AppBundle:Usuarios:index" }
    methods:  GET

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Usuarios:show" }
    methods:  GET

usuarios_new:
    path:     /new
    defaults: { _controller: "AppBundle:Usuarios:new" }
    methods:  [GET, POST]

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Usuarios:edit" }
    methods:  [GET, POST]

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Usuarios:delete" }
    methods:  DELETE
