vendedores_index:
    path:     /
    defaults: { _controller: "AppBundle:Vendedores:index" }
    methods:  GET

vendedores_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Vendedores:show" }
    methods:  GET

vendedores_new:
    path:     /new
    defaults: { _controller: "AppBundle:Vendedores:new" }
    methods:  [GET, POST]

vendedores_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Vendedores:edit" }
    methods:  [GET, POST]

vendedores_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Vendedores:delete" }
    methods:  DELETE
