app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"
    prefix:   /usuarios

app_sellers:
    resource: "@AppBundle/Resources/config/routing/sellers.yml"
    prefix:   /vendedor

app_manager:
    resource: "@AppBundle/Resources/config/routing/manager.yml"
    prefix:   /generente