app_usuarios:
  resource: "@AppBundle/Resources/config/routing/usuarios.yml"
  prefix:   /usuarios

app_bodega:
  resource: "@AppBundle/Resources/config/routing/bodega.yml"
  prefix:   /bodega

app_producto:
  resource: "@AppBundle/Resources/config/routing/producto.yml"
  prefix:   /producto

app_clientes:
  resource: "@AppBundle/Resources/config/routing/clientes.yml"
  prefix:   /clientes

app_cobradores:
  resource: "@AppBundle/Resources/config/routing/cobradores.yml"
  prefix:   /cobradores

app_detalle:
  resource: "@AppBundle/Resources/config/routing/detalle.yml"
  prefix:   /detalle

app_historialdeudor:
  resource: "@AppBundle/Resources/config/routing/historialdeudor.yml"
  prefix:   /historialdeudor

app_vendedores:
  resource: "@AppBundle/Resources/config/routing/vendedores.yml"
  prefix:   /vendedores

app_movimientos:
  resource: "@AppBundle/Resources/config/routing/movimientos.yml"
  prefix:   /movimientos