app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"
    prefix:   /usuarios

app_operators:
    resource: "@AppBundle/Resources/config/routing/operators.yml"
    prefix:   /operador

app_manager:
    resource: "@AppBundle/Resources/config/routing/manager.yml"
    prefix:   /gerente
